/* Project Base VMO
 * Created Date: 24/07/2023
 * Created By: LocHN
 * Descript: Common constant String
 * PIC: LocHN
 */
public with sharing class VMO_CommonConstant {
    public static String DEFAULT_ERROR_MESS = 'Intenal Error!';
    public static String CREATETICKET_SUCCESS = 'Ticket created successfully!';
    public static String CREATETICKET_FALSE = 'Create Ticket Failed: ';
    public static String SUBEJCT_FALSE = 'Please input Subject !';
    public static String UPDATE_SUBJECT_FALSE = 'Cannot update the Subject field.';
}
